<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <RootNamespace>WinEvo.Actions.Operations</RootNamespace>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" />
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinEvo.Actions.Abstractions\WinEvo.Actions.Abstractions.csproj" />
    <ProjectReference Include="..\WinEvo.Tools.Sysinternals\WinEvo.Tools.Sysinternals.csproj" />
  </ItemGroup>

</Project>
